## Kaggle – DataTops®
Luismi ha decidido cambiar de aires y, por eso, ha comprado una tienda de portátiles. Sin embargo, su única especialidad es Data Science, por lo que ha decidido crear un modelo de ML para establecer los mejores precios.

¿Podrías ayudar a Luismi a mejorar ese modelo?

## Métrica: 
Error de raíz cuadrada media (RMSE) es la desviación estándar de los valores residuales (errores de predicción). Los valores residuales son una medida de la distancia de los puntos de datos de la línea de regresión; RMSE es una medida de cuál es el nivel de dispersión de estos valores residuales. En otras palabras, le indica el nivel de concentración de los datos en la línea de mejor ajuste.


$$ RMSE = \sqrt{\frac{1}{n}\Sigma_{i=1}^{n}{\Big(\frac{d_i -f_i}{\sigma_i}\Big)^2}}$$

## Librerías

In [183]:
import numpy as np
import pandas as pd
import toolbox_ML as tb


from PIL import Image
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
import urllib.request

## Datos

In [184]:
# Para que funcione necesitas bajarte los archivos de datos de Kaggle 
df = pd.read_csv("./data/train.csv", index_col = 0)
df.index.name = None

In [185]:
df_bck_up = df.copy()

## Exploración de los datos

In [186]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 912 entries, 755 to 229
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           912 non-null    object
 1   Product           912 non-null    object
 2   TypeName          912 non-null    object
 3   Inches            912 non-null    float64
 4   ScreenResolution  912 non-null    object
 5   Cpu               912 non-null    object
 6   Ram               912 non-null    object
 7   Memory            912 non-null    object
 8   Gpu               912 non-null    object
 9   OpSys             912 non-null    object
 10  Weight            912 non-null    object
 11  Price_in_euros    912 non-null    float64
dtypes: float64(2), object(10)
memory usage: 92.6+ KB

In [187]:
df.isna().sum()

Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_in_euros      0
dtype: int64

In [188]:
df.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_in_euros
755,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.86kg,539.00
618,Dell,Inspiron 7559,Gaming,15.6,Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,16GB,1TB HDD,Nvidia GeForce GTX 960<U+039C>,Windows 10,2.59kg,879.01
909,HP,ProBook 450,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,Nvidia GeForce 930MX,Windows 10,2.04kg,900.00
2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
286,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2.0GHz,4GB,1TB HDD,AMD Radeon R5 M430,Linux,2.25kg,428.00

In [189]:
df.tail()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_in_euros
28,Dell,Inspiron 5570,Notebook,15.6,Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,AMD Radeon 530,Windows 10,2.2kg,800.00
1160,HP,Spectre Pro,2 in 1 Convertible,13.3,Full HD / Touchscreen 1920x1080,Intel Core i5 6300U 2.4GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.48kg,1629.00
78,Lenovo,IdeaPad 320-15IKBN,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,2TB HDD,Intel HD Graphics 620,No OS,2.2kg,519.00
23,HP,255 G6,Notebook,15.6,1366x768,AMD E-Series E2-9000e 1.5GHz,4GB,500GB HDD,AMD Radeon R2,No OS,1.86kg,258.00
229,Dell,Alienware 17,Gaming,17.3,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,4.42kg,2456.34

In [190]:
tb.describe_df(df)

                 DATA_TYPE MISSINGS (%) UNIQUE_VALUES CARDIN (%)
Company             object            0            19       2.08
Product             object            0           480      52.63
TypeName            object            0             6       0.66
Inches             float64            0            17       1.86
ScreenResolution    object            0            36       3.95
Cpu                 object            0           107      11.73
Ram                 object            0             9       0.99
Memory              object            0            37       4.06
Gpu                 object            0            93       10.2
OpSys               object            0             9       0.99
Weight              object            0           165      18.09
Price_in_euros     float64            0           603      66.12

In [191]:
tb.tipifica_variables(df)

            variable               tipo
0            Company  Numérica Discreta
1            Product  Numérica Continua
2           TypeName         Categórica
3             Inches  Numérica Discreta
4   ScreenResolution  Numérica Discreta
5                Cpu  Numérica Discreta
6                Ram         Categórica
7             Memory  Numérica Discreta
8                Gpu  Numérica Discreta
9              OpSys         Categórica
10            Weight  Numérica Continua
11    Price_in_euros  Numérica Continua

## Procesado de datos

In [192]:
df[df.duplicated()].sort_values("Product")

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_in_euros
1305,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1295,Acer,Aspire ES1-531,Notebook,15.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,500GB HDD,Intel HD Graphics 400,Linux,2.4kg,289.00
1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1304,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1283,Lenovo,IdeaPad Y700-15ISK,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,8GB,1TB HDD,Nvidia GeForce GTX 960M,Windows 10,2.6kg,899.00
1311,Lenovo,IdeaPad Y700-15ISK,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,8GB,1TB HDD,Nvidia GeForce GTX 960M,Windows 10,2.6kg,899.00
1310,Dell,Inspiron 3552,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,500GB HDD,Intel HD Graphics,Windows 10,2.20kg,379.00
1285,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,AMD Radeon R5 M430,Linux,2.3kg,805.99
1294,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i3 7100U 2.4GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows 10,2.3kg,459.00
1313,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,AMD Radeon R5 M430,Linux,2.3kg,805.99
1298,HP,Pavilion 15-AW003nv,Notebook,15.6,Full HD 1920x1080,AMD A9-Series 9410 2.9GHz,6GB,1.0TB Hybrid,AMD Radeon R7 M440,Windows 10,2.04kg,549.99
1286,HP,Stream 11-Y000na,Netbook,11.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,2GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,1.17kg,209.00
1306,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00
1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00
1315,Asus,X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,4GB,500GB HDD,Nvidia GeForce 920M,Windows 10,2.2kg,720.32
1287,Asus,X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,4GB,500GB HDD,Nvidia GeForce 920M,Windows 10,2.2kg,720.32
1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1302,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1303,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1289,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1279,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core M 6Y30 0.9GHz,8GB,512GB SSD,Intel HD Graphics 515,Windows 10,1.2kg,729.00

In [193]:
# Viendo esos duplicados uno a uno, procedemos a eliminar los que realmente están duplicados utilizando su índice:
df.drop(index = [1313, 1318, 1320, 1315, 1316, 1303], inplace = True)

In [194]:
df["inches"] = df.Inches.astype(float)
df['ram_gb'] = df['Ram'].str.replace('GB', '').astype(int)
df["weight_kg"] = df['Weight'].str.replace('kg', '').astype(float)
df.drop(columns = ["Inches", "Ram", "Weight"], inplace = True)

In [195]:
# Ordenamos las features categóricas de menor precio de median a mayor precio para poder convertirlas en numéricas:
categories_company = df.groupby(df["Company"])["Price_in_euros"].median().sort_values().index.to_list()
# categories_typename = df.groupby(df["TypeName"])["Price_in_euros"].median().sort_values().index.to_list()
categories_resolution = df.groupby(df["ScreenResolution"])["Price_in_euros"].median().sort_values().index.to_list()
categories_cpu = df.groupby(df["Cpu"])["Price_in_euros"].median().sort_values().index.to_list()
categories_memory = df.groupby(df["Memory"])["Price_in_euros"].median().sort_values().index.to_list()
categories_gpu = df.groupby(df["Gpu"])["Price_in_euros"].median().sort_values().index.to_list()

total_cat = [categories_company, categories_resolution, categories_cpu, categories_memory, categories_gpu]
cols = ["Company", "ScreenResolution", "Cpu", "Memory", "Gpu"]

enc = OrdinalEncoder(categories = total_cat, dtype= int, handle_unknown = "use_encoded_value", unknown_value = -1)
df[cols] = enc.fit_transform(df[cols])
df.head()

,Company,Product,TypeName,ScreenResolution,Cpu,Memory,Gpu,OpSys,Price_in_euros,inches,ram_gb,weight_kg
755,8,250 G6,Notebook,11,33,20,43,Windows 10,539.00,15.6,8,1.86
618,7,Inspiron 7559,Gaming,11,77,11,45,Windows 10,879.01,15.6,16,2.59
909,8,ProBook 450,Notebook,11,67,11,40,Windows 10,900.00,15.6,8,2.04
2,11,Macbook Air,Ultrabook,10,58,14,38,macOS,898.94,13.3,8,1.34
286,7,Inspiron 3567,Notebook,11,32,11,16,Linux,428.00,15.6,4,2.25

In [196]:
df = pd.get_dummies(df, columns = ["TypeName", "OpSys", "ram_gb"], dtype = int)

In [197]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 906 entries, 755 to 229
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Company                      906 non-null    int32
 1   Product                      906 non-null    object
 2   ScreenResolution             906 non-null    int32
 3   Cpu                          906 non-null    int32
 4   Memory                       906 non-null    int32
 5   Gpu                          906 non-null    int32
 6   Price_in_euros               906 non-null    float64
 7   inches                       906 non-null    float64
 8   weight_kg                    906 non-null    float64
 9   TypeName_2 in 1 Convertible  906 non-null    int32
 10  TypeName_Gaming              906 non-null    int32
 11  TypeName_Netbook             906 non-null    int32
 12  TypeName_Notebook            906 non-null    int32
 13  TypeName_Ultrabook           906 non-null    int32
 14  TypeName_Workstation         906 non-null    int32
 15  OpSys_Android                906 non-null    int32
 16  OpSys_Chrome OS              906 non-null    int32
 17  OpSys_Linux                  906 non-null    int32
 18  OpSys_Mac OS X               906 non-null    int32
 19  OpSys_No OS                  906 non-null    int32
 20  OpSys_Windows 10             906 non-null    int32
 21  OpSys_Windows 10 S           906 non-null    int32
 22  OpSys_Windows 7              906 non-null    int32
 23  OpSys_macOS                  906 non-null    int32
 24  ram_gb_2                     906 non-null    int32
 25  ram_gb_4                     906 non-null    int32
 26  ram_gb_6                     906 non-null    int32
 27  ram_gb_8                     906 non-null    int32
 28  ram_gb_12                    906 non-null    int32
 29  ram_gb_16                    906 non-null    int32
 30  ram_gb_24                    906 non-null    int32
 31  ram_gb_32                    906 non-null    int32
 32  ram_gb_64                    906 non-null    int32
dtypes: float64(3), int32(29), object(1)
memory usage: 138.0+ KB

Nuestro target es la columna `Price_in_euros`

In [198]:
target = "Price_in_euros"

-----------------------------------------------------------------------------------------------------------------

## Modelado

### 1. Definir X e y

In [199]:
X = df.drop(columns = [target, "Product"])
y = df[target]

### 2. Dividir X_train, X_test, y_train, y_test

In [200]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [201]:
X_train.head()

,Company,ScreenResolution,Cpu,Memory,Gpu,inches,weight_kg,TypeName_2 in 1 Convertible,TypeName_Gaming,TypeName_Netbook,...,OpSys_macOS,ram_gb_2,ram_gb_4,ram_gb_6,ram_gb_8,ram_gb_12,ram_gb_16,ram_gb_24,ram_gb_32,ram_gb_64
153,7,11,82,30,46,15.6,2.56,0,1,0,...,0,0,0,0,0,0,1,0,0,0
275,11,23,92,30,74,13.3,1.37,0,0,0,...,1,0,0,0,1,0,0,0,0,0
111,13,11,82,29,60,15.6,2.20,0,1,0,...,0,0,0,0,0,0,1,0,0,0
207,5,13,82,34,70,15.6,3.20,0,1,0,...,0,0,0,0,0,0,1,0,0,0
771,16,26,81,20,66,12.3,1.10,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [202]:
y_train.head()

153    1249.26
275    1958.90
111    1299.00
207    1749.00
771    1559.00
Name: Price_in_euros, dtype: float64

### 3. Baseline de modelos

In [203]:
rfmodel = RandomForestRegressor()

rfmodel.fit(X_train, y_train)

RandomForestRegressor()

In [204]:
y_pred = rfmodel.predict(X_test)

### 4. Sacar métricas, valorar los modelos 

Recuerda que en la competición se va a evaluar con la métrica de ``RMSE``.

In [205]:
print(np.sqrt(mean_squared_error(y_test, y_pred)))

251.93356563483601

-----------------------------------------------------------------

## Una vez listo el modelo, toca predecir ``test.csv``

**RECUERDA: APLICAR LAS TRANSFORMACIONES QUE HAYAS REALIZADO EN `train.csv` a `test.csv`.**


Véase:
- Estandarización/Normalización
- Eliminación de Outliers
- Eliminación de columnas
- Creación de columnas nuevas
- Gestión de valores nulos
- Y un largo etcétera de técnicas que como Data Scientist hayas considerado las mejores para tu dataset.

### 1. Carga los datos de `test.csv` para predecir.

In [206]:
X_pred = pd.read_csv("data/test.csv", index_col = 0)
X_pred.index.name = None
X_pred.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
209,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,512GB SSD,Nvidia GeForce GTX 1060,No OS,2.4kg
1281,Acer,Aspire ES1-531,Notebook,15.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,500GB HDD,Intel HD Graphics 400,Linux,2.4kg
1168,Lenovo,V110-15ISK (i3-6006U/4GB/1TB/No,Notebook,15.6,1366x768,Intel Core i3 6006U 2.0GHz,4GB,1TB HDD,Intel HD Graphics 520,No OS,1.9kg
1231,Dell,Inspiron 7579,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.191kg
1020,HP,ProBook 640,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.95kg

In [207]:
X_pred.tail()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
820,MSI,GE72MVR 7RG,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,512GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,Windows 10,2.9kg
948,Toshiba,Tecra Z40-C-12X,Notebook,14.0,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.47kg
483,Dell,Precision M5520,Workstation,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8GB,256GB SSD,Nvidia Quadro M1200,Windows 10,1.78kg
1017,HP,Probook 440,Notebook,14.0,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,Windows 10,1.64kg
421,Asus,ZenBook Flip,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.27kg

In [208]:
X_pred.info()

<class 'pandas.core.frame.DataFrame'>
Index: 391 entries, 209 to 421
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           391 non-null    object
 1   Product           391 non-null    object
 2   TypeName          391 non-null    object
 3   Inches            391 non-null    float64
 4   ScreenResolution  391 non-null    object
 5   Cpu               391 non-null    object
 6   Ram               391 non-null    object
 7   Memory            391 non-null    object
 8   Gpu               391 non-null    object
 9   OpSys             391 non-null    object
 10  Weight            391 non-null    object
dtypes: float64(1), object(10)
memory usage: 36.7+ KB

 ## 2. Replicar el procesado para ``test.csv``

In [209]:
X_pred["inches"] = X_pred.Inches.astype(float)
X_pred['ram_gb'] = X_pred['Ram'].str.replace('GB', '').astype(int)
X_pred["weight_kg"] = X_pred['Weight'].str.replace('kg', '').astype(float)
X_pred.drop(columns = ["Inches", "Ram", "Weight", "Product"], inplace = True)

In [210]:
X_pred.info()

<class 'pandas.core.frame.DataFrame'>
Index: 391 entries, 209 to 421
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           391 non-null    object
 1   TypeName          391 non-null    object
 2   ScreenResolution  391 non-null    object
 3   Cpu               391 non-null    object
 4   Memory            391 non-null    object
 5   Gpu               391 non-null    object
 6   OpSys             391 non-null    object
 7   inches            391 non-null    float64
 8   ram_gb            391 non-null    int32
 9   weight_kg         391 non-null    float64
dtypes: float64(2), int32(1), object(7)
memory usage: 32.1+ KB

In [211]:
# # Ordenamos las features categóricas de menor precio de median a mayor precio para poder convertirlas en numéricas:
# categories_company = df.groupby(df["Company"])["Price_in_euros"].median().sort_values().index.to_list()
# # categories_typename = df.groupby(df["TypeName"])["Price_in_euros"].median().sort_values().index.to_list()
# categories_resolution = df.groupby(df["ScreenResolution"])["Price_in_euros"].median().sort_values().index.to_list()
# categories_cpu = df.groupby(df["Cpu"])["Price_in_euros"].median().sort_values().index.to_list()
# categories_memory = df.groupby(df["Memory"])["Price_in_euros"].median().sort_values().index.to_list()
# categories_gpu = df.groupby(df["Gpu"])["Price_in_euros"].median().sort_values().index.to_list()

# total_cat = [categories_company, categories_resolution, categories_cpu, categories_memory, categories_gpu]
# cols = ["Company", "ScreenResolution", "Cpu", "Memory", "Gpu"]

# enc = OrdinalEncoder(categories = total_cat, dtype= int)
X_pred[cols] = enc.transform(X_pred[cols])

# Con la ram, el sistema operativo y el typename, vamos a hacer un get_dummies:
cols_dummies = X_train.columns
X_pred = pd.get_dummies(X_pred, columns = ["TypeName", "OpSys", "ram_gb"], dtype = int).reindex(columns = cols_dummies, fill_value=0)

In [212]:
X_pred.head()

,Company,ScreenResolution,Cpu,Memory,Gpu,inches,weight_kg,TypeName_2 in 1 Convertible,TypeName_Gaming,TypeName_Netbook,...,OpSys_macOS,ram_gb_2,ram_gb_4,ram_gb_6,ram_gb_8,ram_gb_12,ram_gb_16,ram_gb_24,ram_gb_32,ram_gb_64
209,5,11,82,30,70,15.6,2.400,0,1,0,...,0,0,0,0,0,0,1,0,0,0
1281,3,3,8,7,2,15.6,2.400,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1168,5,3,32,11,43,15.6,1.900,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1231,7,14,52,20,41,15.6,2.191,1,0,0,...,0,0,0,0,1,0,0,0,0,0
1020,8,11,52,20,41,14.0,1.950,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [213]:
predictions_submit = rfmodel.predict(X_pred)
predictions_submit

array([1509.3566    ,  284.5259    ,  386.2313    ,  842.9377    ,
        879.1137    ,  476.08871667,  882.1145    ,  891.8482    ,
        958.2754    ,  365.84      , 2308.8764    , 1407.5285    ,
        516.25748333, 1491.3954    ,  829.7937    ,  776.4277    ,
       1661.6951    , 1606.6908    , 1545.999     ,  733.3494    ,
       1364.9644    ,  253.705     ,  833.0115    , 1522.2157    ,
        464.2484    ,  688.1005    ,  505.6871    ,  288.3989    ,
       4485.2926    ,  908.4686    , 2310.5876    ,  430.3365    ,
        787.1188    , 3045.7725    , 2232.851     , 1493.768     ,
        651.8481    ,  497.2425    , 1031.4798    , 1657.8504    ,
        719.9312    ,  814.409     ,  569.9381    , 1222.4697    ,
        911.7371    , 1062.17      ,  960.5395    ,  571.8856    ,
        695.6247    ,  364.9198    , 1722.0928    ,  714.475     ,
       1119.991     ,  702.9513    , 1968.7014    , 1658.013     ,
        758.9118    ,  884.82143333,  854.786     ,  613.7755    ,
        696.5275    , 1570.8437    ,  497.8072    , 2038.378     ,
       1639.2482    , 1219.8477    ,  872.8042    ,  927.2928    ,
       1970.136     , 1813.4579    ,  764.82996667,  314.438     ,
       1001.7245    , 1420.79573333,  997.4935    , 1445.619     ,
       1850.657     , 1750.4151    , 2291.9536    , 1290.5075    ,
        838.6526    , 1716.2189    , 2226.2989    , 1499.7523    ,
       1501.7969    , 1784.532     ,  435.4861    ,  964.041     ,
        634.1549    ,  979.22      ,  561.95585   , 1714.3128    ,
       1527.6365    , 2465.01025333, 3866.8233    , 1259.7526    ,
        733.678     ,  511.94568333,  387.6726    ,  957.3753    ,
       1857.4653    ,  682.7231    , 1472.5016    , 1182.6944    ,
        258.3943    , 1416.1473    , 1828.56046667,  661.2312    ,
        370.11142857,  973.4104    , 1492.44446667,  970.498     ,
        733.5266    ,  663.9422    , 1173.2381    ,  664.2116    ,
        632.9536    , 1032.1894    , 1791.58268333, 1142.09356667,
        868.5765    ,  755.3067    , 1074.6942    , 1504.89      ,
       1899.5076    ,  539.8258    , 1887.0107    ,  845.0326    ,
        561.6221    ,  777.9762    , 1104.0431    , 1477.1749    ,
       1181.6       , 1487.3299    ,  814.7325    , 1823.1819    ,
       1052.9043    ,  965.6063    , 1364.71      ,  602.3477    ,
       1387.69506667,  700.6649    , 1264.86      , 1123.6471    ,
        531.45416667, 1142.09356667, 1418.0258    ,  713.2416    ,
       1277.3774    ,  830.9022    ,  763.7468    ,  774.3223    ,
        298.6994    ,  826.1055    ,  595.8395    ,  908.2826    ,
       1138.8431    ,  964.121     ,  960.7716    ,  359.3099    ,
        448.3942    , 1822.40203333, 1463.405865  ,  635.343     ,
       1196.90663333,  953.1222    , 2003.6525    ,  219.676     ,
        834.6851    ,  873.5514    , 1519.28747   ,  451.5853    ,
        356.5696    ,  611.5091    , 2258.3337    ,  742.5336    ,
        906.3599    ,  520.763     , 1230.6517    , 1194.77246667,
        647.7809    , 5372.342     , 1210.3799    ,  838.23633333,
       1391.9427    , 1962.342     ,  312.6271    ,  904.1049    ,
       1488.848     ,  908.4384    ,  628.7012    , 1788.26466667,
        433.35064   ,  837.82616667,  602.8899    ,  279.9589    ,
       1473.9487    ,  948.4261    ,  680.596     ,  286.61346667,
       1074.6942    , 2032.1076    , 1357.677     ,  606.851     ,
        632.0018    ,  295.01893333, 1197.7338    ,  328.0058    ,
       2009.50833333,  362.4484    ,  870.50416667,  912.9517    ,
        946.5874    , 1007.2408    ,  570.8262    , 1545.8992    ,
        935.4799    ,  655.8801    ,  734.9663    ,  468.7292    ,
        400.853     , 1323.54896667, 1073.1437    , 1285.4642    ,
        837.3007    , 1108.5051    ,  281.1574    , 1174.7965    ,
        790.7128    , 1711.3328    ,  475.2881    ,  462.4805    ,
        888.4045    , 1376.71006667,  350.5526    ,  713.2416    ,
       2509.04523333,  992.7306    ,  849.5274    , 1416.4366    ,
       1725.49      ,  590.6119    ,  940.1486    , 1297.9401    ,
        936.4411    , 2098.514     , 1260.9906    ,  773.2277    ,
        892.1378    , 1731.7138    , 1250.0842    ,  480.6575    ,
       1445.5732    ,  856.2731    , 1445.5732    , 2710.8989    ,
        584.9601    ,  463.8972    , 1287.857     ,  919.33456667,
        458.5921    ,  565.01      , 1056.5305    ,  483.2105    ,
       2282.7675    , 3889.7695    ,  980.671     ,  305.68223333,
       2274.588     , 1448.1106    ,  416.4162    ,  575.2408    ,
        958.3636    , 1296.4931    , 1501.7439    ,  745.04453333,
        497.3927    ,  695.8677    , 1127.4414    ,  466.77476   ,
        559.7494    ,  891.5983    , 1305.30466667,  563.6989    ,
        355.326     , 1051.1135    ,  928.9647    , 2212.0611    ,
       3155.6275    ,  550.5998    , 1020.39      , 1440.7316    ,
       1530.7094    , 1537.2683    ,  370.7996    , 1580.7045    ,
       1384.5577    ,  860.06166667, 1002.6286    , 1501.9891    ,
       1585.77336667,  622.6213    ,  289.035     ,  467.701     ,
        727.9019    ,  427.9782    , 1024.9832    ,  733.26216667,
       1857.4473    , 1258.7221    ,  436.9944    ,  900.3026    ,
        359.83026667,  463.1729    ,  830.605     , 1324.5045    ,
       2702.2986    , 1050.8948    , 1048.4424    ,  752.93633333,
       1560.5743    ,  839.9349    , 1174.7293    , 1349.327     ,
       1382.4047    , 2075.2425    , 1992.19483333,  512.04721667,
        463.7178    , 2051.9132    ,  432.3257    , 1040.2143    ,
       1503.166     ,  622.7741    ,  422.723     , 1123.8322    ,
        464.3328    ,  550.5998    , 1635.9597    , 1290.513     ,
        310.4935    ,  495.4846    , 1560.0478    , 1523.35133333,
       1725.49      ,  806.1367    ,  368.3719    , 1353.93028333,
        741.4892    ,  692.5978    , 1011.563     ,  886.5761    ,
        662.0478    ,  460.1936    ,  639.0062    ,  347.6761    ,
       1870.308     ,  725.319     ,  997.8046    , 1942.3454    ,
        487.4949    ,  744.2997    ,  846.5007    , 1378.08      ,
       1208.3017    , 1277.3437    , 1801.1844    , 4037.5548    ,
        627.7242    , 1984.193     , 1264.05363333, 1694.7091    ,
        631.3442    , 1518.7068    , 1403.2422    , 1924.0856    ,
        559.7494    ,  907.57283333,  555.3445    ,  845.216     ,
        492.2548    ,  985.6571    , 1202.2699    ,  313.16553333,
       1722.0249    ,  863.669     , 2207.8428    ,  960.3419    ,
       1797.2086    ,  932.3935    , 1404.8354    ])

### 3. **¿Qué es lo que subirás a Kaggle?**

**Para subir a Kaggle la predicción esta tendrá que tener una forma específica.**

En este caso, la **MISMA** forma que `sample_submission.csv`.

In [214]:
sample = pd.read_csv("data/sample_submission.csv")

In [215]:
sample.head()

   laptop_ID  Price_in_euros
0        209          1949.1
1       1281           805.0
2       1168          1101.0
3       1231          1293.8
4       1020          1832.6

In [216]:
sample.shape

(391, 2)

### 4. Mete tus predicciones en un dataframe llamado ``submission``.

In [217]:
#¿Cómo creamos la submission?
submission = pd.DataFrame({"laptop_ID": X_pred.index,
                        "Price_in_euros": predictions_submit})

In [218]:
submission.head()

   laptop_ID  Price_in_euros
0        209       1509.3566
1       1281        284.5259
2       1168        386.2313
3       1231        842.9377
4       1020        879.1137

In [219]:
submission.shape

(391, 2)

### 5. Pásale el CHEQUEADOR para comprobar que efectivamente está listo para subir a Kaggle.

In [220]:
def chequeador(df_to_submit):
    """
    Esta función se asegura de que tu submission tenga la forma requerida por Kaggle.
    
    Si es así, se guardará el dataframe en un `csv` y estará listo para subir a Kaggle.
    
    Si no, LEE EL MENSAJE Y HAZLE CASO.
    
    Si aún no:
    - apaga tu ordenador, 
    - date una vuelta, 
    - enciendelo otra vez, 
    - abre este notebook y 
    - leelo todo de nuevo. 
    Todos nos merecemos una segunda oportunidad. También tú.
    """
    if df_to_submit.shape == sample.shape:
        if df_to_submit.columns.all() == sample.columns.all():
            if df_to_submit.laptop_ID.all() == sample.laptop_ID.all():
                print("You're ready to submit!")
                submission.to_csv("submission.csv", index = False) #muy importante el index = False
                urllib.request.urlretrieve("https://www.mihaileric.com/static/evaluation-meme-e0a350f278a36346e6d46b139b1d0da0-ed51e.jpg", "gfg.png")     
                img = Image.open("gfg.png")
                img.show()   
            else:
                print("Check the ids and try again")
        else:
            print("Check the names of the columns and try again")
    else:
        print("Check the number of rows and/or columns and try again")
        print("\nMensaje secreto del TA: No me puedo creer que después de todo este notebook hayas hecho algún cambio en las filas de `test.csv`. Lloro.")

In [221]:
chequeador(submission)

You're ready to submit!